version: '3.9'

services:

  app:
    image: case-opener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/case_opener_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=386629
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'case_opener_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: "386629"

  liquibase:
    image: liquibase
    depends_on:
      - postgres
    volumes:
      - /db.changelog-master.yaml
    command: update
